# Core and data
input_shape: [128,2,50,72,64]  # Required at top-level config
n_neurons_dict: ???  # Set dynamically (e.g., in training script after loading sessions)
_target_: openretina.models.core_readout.ViViTCoreReadout
_convert_: object
patch_size: 8
temporal_patch_size: 6
spatial_stride: 6
temporal_stride: 1
Demb: 96
ptoken: 0.2
pad_frame: true
norm: "layernorm"
patch_mode: true
num_heads: 4
num_spatial_blocks: 2
num_temporal_blocks: 2
dropout: 0.3
mlp_ratio: 4.0
learning_rate: 5e-4
channels: 2
readout_bias: true
# training
readout_init_mu_range: 0.05
readout_init_sigma_range: 0.01
readout_gamma: 0.4
readout_reg_avg: false
       